### ISSUE TITLE
Bintray is closing down in May 2021

### ISSUE THREAD

**Issue by akarnokd** [ReactiveX/RxJava#7179]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

I don't fully understand what this means for release processes using `gradle-bintray-plugin` or how to migrate.

**Comment by vanniktech** [comment]
Can't we push to mavenCentral directly?

**Comment by akarnokd** [comment]
There are a few problems:
- The private key is on bintray and can't be extracted, only overwritten. (Maybe @benjchristensen still has it.)
- If we need to generate a new private key, I don't know/remember what to do with it. (It's been years since I setup my own private key for my libraries I release from my machine via your plugin.)
- I don't know how to inject a private key into the GitHub Action. (Having a GH secret string of the key material is one thing, afaik, it has to be imported into a keystore every time so Gradle's sign task can use it.)

**Comment by benjchristensen** [comment]
I have all the ReactiveX keys.

**Comment by vanniktech** [comment]
Secrets can be added to GitHub: https://github.com/vanniktech/gradle-maven-publish-plugin/settings/secrets/actions (replace username / repo with target repo):

<img width="1236" alt="Screenshot 2021-02-03 at 22 46 15" src="https://user-images.githubusercontent.com/5759366/106813686-a0cc1900-6671-11eb-9fd1-ad2736999ccc.png">

And then they can be used in GitHub actions:

```yml
name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Upload release
        run: ./gradlew uploadArchives --no-daemon --no-parallel
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_SIGNING_PRIVATE_KEY: ${{ secrets.SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      - name: Publish release
        run: ./gradlew closeAndReleaseRepoistory --no-daemon --no-parallel
        env:
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
```

[Source](https://github.com/vanniktech/gradle-maven-publish-plugin/blob/master/.github/workflows/publish-release.yml)

They key itself needs to be distributed in order for this to work though. Instructions are [here](https://central.sonatype.org/pages/working-with-pgp-signatures.html).
